# Generated by Django 4.1.5 on 2023-02-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("social", "0010_user_user_online_alter_media_uploaded_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favorite", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="personalfavoirte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorite_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personality.favorite",
                    ),
                ),
                (
                    "personal_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="social.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="personal_dates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="social.user"
                    ),
                ),
            ],
        ),
    ]
