# Generated by Django 4.1.5 on 2023-02-01 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personality", "0002_work_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="work_education",
            name="from_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="work_education",
            name="to_date",
            field=models.DateField(
                default=datetime.datetime(2023, 2, 1, 7, 10, 25, 953133)
            ),
        ),
    ]
