# Generated by Django 4.1.5 on 2023-02-05 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personality", "0004_alter_work_education_to_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work_education",
            name="to_date",
            field=models.DateField(
                default=datetime.datetime(2023, 2, 5, 3, 19, 30, 703221)
            ),
        ),
    ]
