# Generated by Django 4.1.5 on 2023-02-07 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personality", "0008_alter_work_education_to_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="work_education",
            name="city",
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="work_education",
            name="to_date",
            field=models.DateField(
                default=datetime.datetime(2023, 2, 7, 4, 16, 13, 875454)
            ),
        ),
    ]
