# Generated by Django 4.1.5 on 2023-01-23 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="allowed_countrys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.TextField(max_length=25)),
                ("country_id", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="friend_ships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_1", models.BigIntegerField()),
                ("user_2", models.BigIntegerField()),
                ("friend_type", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_content", models.CharField(max_length=10000)),
                ("post_id", models.BigIntegerField()),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 1, 23, 6, 0, 58, 634581)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=45)),
                ("user_email", models.EmailField(max_length=31, null=True)),
                ("user_phone", models.CharField(max_length=30)),
                ("user_id", models.BigIntegerField()),
                (
                    "user_profile_img",
                    models.FileField(
                        default="/media/img/users/find_user.png", upload_to=""
                    ),
                ),
                ("user_country", models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reaction_type", models.CharField(max_length=100)),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="social.post"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="social.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="social.user"
            ),
        ),
        migrations.CreateModel(
            name="media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_link", models.CharField(max_length=100)),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 1, 23, 6, 0, 58, 634581)
                    ),
                ),
                ("media_id", models.BigIntegerField()),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="social.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=40)),
                ("city_id", models.BigIntegerField()),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social.allowed_countrys",
                    ),
                ),
            ],
        ),
    ]
