# Generated by Django 4.1.5 on 2023-01-23 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_alter_media_uploaded_at_alter_post_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 23, 6, 3, 50, 769631)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 23, 6, 3, 50, 770631)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="social.cities"
            ),
        ),
    ]
