# Generated by Django 4.1.5 on 2023-01-23 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_alter_media_uploaded_at_alter_post_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 23, 6, 4, 32, 37580)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 23, 6, 4, 32, 38581)
            ),
        ),
    ]
