# Generated by Django 4.1.5 on 2023-01-24 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_alter_media_uploaded_at_alter_post_uploaded_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allowed_countrys",
            name="country_id",
        ),
        migrations.RemoveField(
            model_name="cities",
            name="city_id",
        ),
        migrations.AlterField(
            model_name="media",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 24, 10, 12, 2, 698471)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 24, 10, 12, 2, 699501)
            ),
        ),
    ]
