# Generated by Django 4.1.5 on 2023-01-24 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_remove_allowed_countrys_country_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 24, 12, 25, 13, 218048)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 24, 12, 25, 13, 219050)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_country",
            field=models.CharField(max_length=40),
        ),
    ]
