# Generated by Django 4.1.5 on 2023-01-25 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0008_remove_user_user_id_alter_media_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_password",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 25, 6, 57, 49, 604466)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 25, 6, 57, 49, 604466)
            ),
        ),
    ]
