# Generated by Django 4.1.5 on 2023-02-01 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0010_user_user_online_alter_media_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 1, 7, 1, 42, 398018)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 1, 7, 1, 42, 399018)
            ),
        ),
    ]
