# Generated by Django 4.1.5 on 2023-02-05 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0013_user_user_background_alter_media_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 5, 3, 19, 30, 671990)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 5, 3, 19, 30, 671990)
            ),
        ),
    ]
